---
name: Packer Action

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # validate templates
      - name: Validate Templates
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var-file=ubuntu2004.pkrvars.hcl -var-file=ubuntu2204.pkrvars.hcl
          target: .
          working_directory: packer/

      # format templates
      - name: Format Templates
        uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          target: .

      
